name: Playwright Tests & Deploy
on:
  # push:
  #  branches: [ master ]
  workflow_dispatch: # allows manual trigger

jobs:
  test-and-deploy:
    runs-on: windows-latest
    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Fix Playwright permissions
      - name: Fix Playwright permissions
        run: chmod +x node_modules/.bin/playwright

      # 5️⃣ Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 6️⃣ Run Playwright tests
      - name: Run Playwright Tests
        run: |
          npx playwright test tests/content
        env:
          ENV: live
        continue-on-error: true  # so we can still deploy report if tests fail

      # 7️⃣ Deploy to Netlify
      - name: Deploy to Netlify
        run: npx netlify deploy --prod --dir=playwright-report --message "Test Deploy"
        env:
          NETLIFY_AUTH_TOKEN: nfp_AQZQLQ4RZXMmTz4U6c8aTVLcqaHUfZrB8079
